Fixed the following issues with the FreeRDS control script: 1) path references to the FreeRDS binaries were incorrect (i.e., sbin directory instead of the bin directory), 2) the FreeRDS Session Manager was not being started or stopped, and 3) a comment still referred to XRDP.

diff --git a/scripts/freerds.sh.in b/scripts/freerds.sh.in
--- a/scripts/freerds.sh.in
+++ b/scripts/freerds.sh.in
@@ -17,14 +17,20 @@
 # Description: starts freerds
 ### END INIT INFO
 
+BINDIR=${FREERDS_BIN_PATH}
 SBINDIR=${FREERDS_SBIN_PATH}
 CFGDIR=${FREERDS_CFG_PATH}
 PIDDIR=${FREERDS_PID_PATH}
 LOG=/dev/null
 
-if ! test -x $SBINDIR/freerds
+if ! test -x $BINDIR/freerds
 then
 	echo "freerds is not executable"
+	exit 0
+fi
+if ! test -x $BINDIR/freerds-session-manager
+then
+	echo "freerds-session-manager is not executable"
 	exit 0
 fi
 if ! test -x $CFGDIR/startwm.sh
@@ -36,7 +42,8 @@ fi
 freerds_start()
 {
 	echo -n "Starting FreeRDS..."
-	$SBINDIR/freerds >> $LOG
+	$BINDIR/freerds >> $LOG
+	$BINDIR/freerds-session-manager >> $LOG
 	echo "."
 	sleep 1
 	return 0;
@@ -45,7 +52,8 @@ freerds_start()
 freerds_stop()
 {
 	echo -n "Stopping FreeRDS..."
-	$SBINDIR/freerds --kill >> $LOG
+	$BINDIR/freerds --kill >> $LOG
+	$BINDIR/freerds-session-manager --kill >> $LOG
 	echo "."
 	return 0;
 }
@@ -57,13 +65,24 @@ is_freerds_running()
 	then
 		return 1;
 	else
-	return 0;
+		return 0;
+	fi
+}
+
+is_freerds_session_manager_running()
+{
+	ps u --noheading -C freerds-session-manager | grep -q -i freerds-session-manager
+	if test $? -eq 0
+	then
+		return 1;
+	else
+		return 0;
 	fi
 }
 
 check_up()
 {
-	# Cleanup : If xrdp isn't running, but the pid exists, erase it.
+	# Cleanup : If freerds isn't running, but the pid exists, erase it.
 	is_freerds_running
 	if test $? -eq 0
 	then
@@ -72,6 +91,16 @@ check_up()
 			rm $PIDDIR/freerds.pid
 		fi
 	fi
+
+	is_freerds_session_manager_running
+	if test $? -eq 0
+	then
+		if test -e $PIDDIR/freerds-session-manager.pid
+		then
+			rm $PIDDIR/freerds-session-manager.pid
+		fi
+	fi
+
 	return 0;
 }
 
@@ -84,6 +113,12 @@ case "$1" in
 			echo "FreeRDS is already running."
 			exit 1
 		fi
+		is_freerds_session_manager_running
+		if ! test $? -eq 0
+		then
+			echo "FreeRDS Session Manager is already running"
+			exit 1
+		fi
 		freerds_start
 		;;
 	stop)
@@ -91,7 +126,12 @@ case "$1" in
 		is_freerds_running
 		if test $? -eq 0
 		then
-			echo "FreeRDS is not running."
+			echo "FreeRDS is not running"
+		fi
+		is_freerds_session_manager_running
+		if test $? -eq 0
+		then
+			echo "FreeRDS Session Manager is not running"
 		fi
 		freerds_stop
 		;;
@@ -105,6 +145,13 @@ case "$1" in
 			check_up
 			sleep 1
 			is_freerds_running
+		done
+		is_freerds_session_manager_running
+		while ! test $? -eq 0
+		do
+			check_up
+			sleep 1
+			is_freerds_session_manager_running
 		done
 		freerds_start
 		;;
